//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTrace_MVCEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO
    {
        public double SAK_CSR { get; set; }
        public Nullable<double> SAK_CSR_TYPE { get; set; }
        public string SAK_RELEASE { get; set; }
        public string SAK_DEFECT_TYPE { get; set; }
        public string SAK_ANY_OBJECT_TYPE { get; set; }
        public Nullable<double> SAK_CO_GROUPING { get; set; }
        public string SAK_TEST_CASE { get; set; }
        public string SAK_LEVEL { get; set; }
        public string SAK_GROUP { get; set; }
        public string NAM { get; set; }
        public Nullable<double> SAK_SUBSYSTEM_AREA { get; set; }
        public string EXTERNAL_ID { get; set; }
        public string DSC { get; set; }
        public string DSC_BUS_IMPACT { get; set; }
        public string DSC_TECH_SPEC { get; set; }
        public string NUM_EST_HOURS { get; set; }
        public string NUM_EST_HOURS_COMPUTED { get; set; }
        public string NUM_PRIORITY { get; set; }
        public string NUM_ACTUAL_HOURS { get; set; }
        public string IND_BILLABLE { get; set; }
        public string IND_SEVERITY { get; set; }
        public string SAK_CUST_SEVERITY { get; set; }
        public string IND_OPERATIONS { get; set; }
        public string IND_ENVIRONMENT { get; set; }
        public string DTE_EST_ITF { get; set; }
        public string DTE_DUE { get; set; }
        public string IND_POST_IMP_WORK { get; set; }
        public Nullable<double> SAK_PROJECT { get; set; }
        public Nullable<double> REFERENCE_CO { get; set; }
        public string CONTRACT_ID { get; set; }
        public Nullable<double> SAK_PARTICIPANT { get; set; }
        public string CURRENT_STATUS_COMMENT { get; set; }
        public string PROVIDER_ID { get; set; }
        public string SAK_DOCUMENT_TYPE { get; set; }
    }
}
