//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTrace_MVCEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_grouping
    {
        public int SAK_CO_GROUPING { get; set; }
        public string NAM { get; set; }
        public string DSC { get; set; }
    }
}
