//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTrace_MVCEF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iTraceEntities : DbContext
    {
        public iTraceEntities()
            : base("name=iTraceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CO> COes { get; set; }
        public virtual DbSet<CO_Grouping> CO_Grouping { get; set; }
        public virtual DbSet<CO_type> CO_type { get; set; }
    }
}
